name: Build Fabric 1.21.4 Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Build with Loom
        run: gradle build # Этот флаг принудительно стирает старые битые пути из памяти сервера
        
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: MaxOptimize-1.21.4
          path: build/libs/*-base.jar
